// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using controleEstoque.Infra.Context;

#nullable disable

namespace controleEstoque.Migrations
{
    [DbContext(typeof(EstoqueContext))]
    [Migration("20250808041647_PrimeiraMigration")]
    partial class PrimeiraMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("controleEstoque.Domain.Entidades.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TBCategorias", (string)null);
                });

            modelBuilder.Entity("controleEstoque.Domain.Entidades.Materiais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<Guid>("categoriaId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("categoriaId");

                    b.ToTable("Materiais", (string)null);
                });

            modelBuilder.Entity("controleEstoque.Domain.Entidades.Movimentacoes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MateriaId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Movimentacoes", (string)null);
                });

            modelBuilder.Entity("controleEstoque.Domain.Entidades.Relatorios", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MateriaisId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("PeriodoReferencia")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TotalEntradas")
                        .HasColumnType("int");

                    b.Property<int>("TotalSaidas")
                        .HasColumnType("int");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("MateriaisId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Relatorios", (string)null);
                });

            modelBuilder.Entity("controleEstoque.Domain.entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConfirmarSenha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("controleEstoque.Domain.Entidades.Materiais", b =>
                {
                    b.HasOne("controleEstoque.Domain.Entidades.Categoria", "Categoria")
                        .WithMany("Materiais")
                        .HasForeignKey("categoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("controleEstoque.Domain.Entidades.Movimentacoes", b =>
                {
                    b.HasOne("controleEstoque.Domain.Entidades.Materiais", "Materiais")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("controleEstoque.Domain.entidades.Usuario", "Usuario")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materiais");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("controleEstoque.Domain.Entidades.Relatorios", b =>
                {
                    b.HasOne("controleEstoque.Domain.Entidades.Materiais", "Materiais")
                        .WithMany()
                        .HasForeignKey("MateriaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("controleEstoque.Domain.entidades.Usuario", null)
                        .WithMany("Relatorios")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Materiais");
                });

            modelBuilder.Entity("controleEstoque.Domain.Entidades.Categoria", b =>
                {
                    b.Navigation("Materiais");
                });

            modelBuilder.Entity("controleEstoque.Domain.Entidades.Materiais", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("controleEstoque.Domain.entidades.Usuario", b =>
                {
                    b.Navigation("Movimentacoes");

                    b.Navigation("Relatorios");
                });
#pragma warning restore 612, 618
        }
    }
}
